# Generated by Django 5.2.10 on 2026-03-04 16:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('term_time_only', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ClimbingRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=10)),
                ('grade_system', models.CharField(choices=[('v_scale', 'V Scale (Bouldering)'), ('font', 'Font Scale'), ('yds', 'YDS (Rope)'), ('uk_tech', 'UK Technical')], default='font', max_length=10)),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('white', 'White'), ('black', 'Black')], max_length=20)),
                ('setter', models.CharField(max_length=100)),
                ('date_set', models.DateField()),
                ('date_removed', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='routes/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_set'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='GymInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Oakwood Climbing Centre', max_length=200)),
                ('address', models.TextField(default='Waterloo Rd, Bracknell, Wokingham RG40 3DA')),
                ('phone', models.CharField(default='0118 979 2246', max_length=20)),
                ('email', models.EmailField(default='enquiries@oakwoodclimbingcentre.com', max_length=254)),
                ('website', models.URLField(default='https://www.oakwoodclimbingcentre.com')),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='gym/')),
                ('monday_hours', models.CharField(default='10:00 - 22:00', max_length=50)),
                ('tuesday_hours', models.CharField(default='10:00 - 22:00', max_length=50)),
                ('wednesday_hours', models.CharField(default='10:00 - 22:00', max_length=50)),
                ('thursday_hours', models.CharField(default='10:00 - 22:00', max_length=50)),
                ('friday_hours', models.CharField(default='10:00 - 22:00', max_length=50)),
                ('saturday_hours', models.CharField(default='10:00 - 18:00', max_length=50)),
                ('sunday_hours', models.CharField(default='10:00 - 18:00', max_length=50)),
                ('peak_info', models.TextField(default='Peak times: Mon-Fri after 4pm, all day weekends & bank holidays')),
            ],
            options={
                'verbose_name': 'Gym Info',
                'verbose_name_plural': 'Gym Info',
            },
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('monthly_adult', 'Monthly Adult'), ('monthly_concession', 'Monthly Concession'), ('monthly_family', 'Monthly Family'), ('punch_card_10', 'Punch Card (10 Visits)'), ('day_pass_peak', 'Day Pass (Peak)'), ('day_pass_offpeak', 'Day Pass (Off-Peak)'), ('day_pass_morning', 'Morning Discount'), ('under_18_peak', 'Under 18 (Peak)'), ('under_18_offpeak', 'Under 18 (Off-Peak)')], max_length=30, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('min_commitment_months', models.PositiveIntegerField(default=0)),
                ('cancellation_notice_months', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='WallSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('wall_type', models.CharField(choices=[('bouldering', 'Bouldering'), ('top_rope', 'Top Rope'), ('lead', 'Lead'), ('auto_belay', 'Auto Belay'), ('kids', 'Kids Zone'), ('outdoor', 'Outdoor'), ('training', 'Training Area')], max_length=20)),
                ('height_metres', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='walls/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('is_published', models.BooleanField(default=True)),
                ('publish_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('waitlisted', 'Waitlisted'), ('attended', 'Attended'), ('no_show', 'No Show')], default='confirmed', max_length=20)),
                ('participants', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('class_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.classschedule')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('member', 'class_schedule', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BirthdayPartyBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100)),
                ('child_age', models.PositiveIntegerField()),
                ('num_children', models.PositiveIntegerField()),
                ('num_adults', models.PositiveIntegerField(default=0)),
                ('special_requirements', models.TextField(blank=True)),
                ('guardian_name', models.CharField(max_length=100)),
                ('guardian_phone', models.CharField(max_length=20)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='party_details', to='api.booking')),
            ],
        ),
        migrations.CreateModel(
            name='CapacitySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_capacity', models.PositiveIntegerField(default=100)),
                ('peak_capacity', models.PositiveIntegerField(default=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Capacity Setting',
                'verbose_name_plural': 'Capacity Settings',
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(blank=True, max_length=100)),
                ('entry_type', models.CharField(choices=[('membership', 'Membership'), ('day_pass', 'Day Pass'), ('punch_card', 'Punch Card'), ('class_booking', 'Class Booking'), ('party', 'Birthday Party'), ('spectator', 'Spectator')], max_length=20)),
                ('checked_in_at', models.DateTimeField(auto_now_add=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_processed', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-checked_in_at'],
            },
        ),
        migrations.CreateModel(
            name='GymClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_type', models.CharField(choices=[('boulder_taster', 'Boulder Taster'), ('auto_belay_induction', 'Auto Belay Induction'), ('beginner_rope', "Beginner's Rope Course"), ('lead_climbing', 'Lead Climbing'), ('coaching', 'Coaching Session'), ('private_session', 'Private Session'), ('adult_social', 'Adult Social'), ('youth_session', 'Youth Session'), ('nicas', 'NICAS Course'), ('nibas', 'NIBAS Course'), ('yoga', 'Yoga for Climbers'), ('birthday_party', 'Birthday Party')], max_length=25)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('all_levels', 'All Levels')], default='all_levels', max_length=20)),
                ('age_group', models.CharField(choices=[('adult', 'Adult (18+)'), ('youth_5_7', 'Youth (5-7)'), ('youth_7_12', 'Youth (7-12)'), ('youth_13_17', 'Youth (13-17)'), ('all_ages', 'All Ages (4+)')], default='adult', max_length=20)),
                ('max_participants', models.PositiveIntegerField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('includes_shoe_hire', models.BooleanField(default=False)),
                ('requires_safety_signoff', models.CharField(blank=True, help_text='Required SafetySignOff type, if any', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='classes/')),
                ('is_active', models.BooleanField(default=True)),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_taught', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Gym Classes',
            },
        ),
        migrations.AddField(
            model_name='classschedule',
            name='gym_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.gymclass'),
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('staff', 'Staff'), ('instructor', 'Instructor'), ('duty_manager', 'Duty Manager'), ('admin', 'Admin')], default='member', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('climbing_since', models.DateField(blank=True, null=True)),
                ('is_student', models.BooleanField(default=False)),
                ('is_nhs', models.BooleanField(default=False)),
                ('is_military', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('pending_cancellation', 'Pending Cancellation'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=25)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('frozen_until', models.DateField(blank=True, null=True)),
                ('cancellation_requested_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_effective_date', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='api.membershipplan')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PunchCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.PositiveIntegerField(default=10)),
                ('remaining_visits', models.PositiveIntegerField(default=10)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RouteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_type', models.CharField(choices=[('flash', 'Flash'), ('send', 'Send'), ('attempt', 'Attempt'), ('project', 'Project')], max_length=20)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('climber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_logs', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.climbingroute')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('open', 'Opening'), ('close', 'Closing'), ('day', 'Day Shift'), ('evening', 'Evening Shift'), ('weekend', 'Weekend Shift')], max_length=20)),
                ('shift_role', models.CharField(choices=[('reception', 'Reception'), ('instructor', 'Instructor'), ('duty_manager', 'Duty Manager'), ('route_setter', 'Route Setter'), ('general', 'General')], default='general', max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_key_holder', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiver_type', models.CharField(choices=[('adult', 'Adult Waiver'), ('under_18', 'Under 18 Guardian Waiver')], max_length=20)),
                ('guardian_name', models.CharField(blank=True, max_length=100)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('guardian_relationship', models.CharField(blank=True, max_length=50)),
                ('has_medical_conditions', models.BooleanField(default=False)),
                ('medical_details', models.TextField(blank=True)),
                ('accepts_terms', models.BooleanField(default=False)),
                ('accepts_photo_consent', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-signed_at'],
            },
        ),
        migrations.AddField(
            model_name='climbingroute',
            name='wall_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='api.wallsection'),
        ),
        migrations.CreateModel(
            name='SafetySignOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_off_type', models.CharField(choices=[('bouldering', 'Bouldering Health & Safety'), ('auto_belay', 'Auto Belay Induction'), ('top_rope', 'Top Rope Competency'), ('lead', 'Lead Climbing Competency')], max_length=20)),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_signoffs', to=settings.AUTH_USER_MODEL)),
                ('signed_off_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signoffs_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_signed'],
                'unique_together': {('member', 'sign_off_type')},
            },
        ),
        migrations.CreateModel(
            name='StaffQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_type', models.CharField(choices=[('cwa', 'Climbing Wall Award'), ('cwi', 'Climbing Wall Instructor'), ('rci', 'Rock Climbing Instructor'), ('mia', 'Mountain Instructor Award'), ('first_aid', 'First Aid'), ('safeguarding', 'Safeguarding'), ('nicas_tutor', 'NICAS Tutor'), ('nibas_tutor', 'NIBAS Tutor')], max_length=20)),
                ('awarded_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('certificate_number', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_date'],
                'unique_together': {('staff_member', 'qualification_type')},
            },
        ),
    ]
