# Generated by Django 5.2.10 on 2026-03-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbingroute',
            name='grade_system',
            field=models.CharField(choices=[('v_scale', 'V Scale (Bouldering)'), ('font', 'Font Scale'), ('yds', 'YDS (Rope)'), ('uk_tech', 'UK Technical'), ('french', 'French Sport')], default='font', max_length=10),
        ),
    ]
